<?php
  /**
   * Engage Commerce
   *
   * NOTICE OF LICENSE
   *
   * This source file is subject to the Open Software License (OSL 3.0)
   * that is bundled with this package in the file LICENSE.txt.
   * It is also available through the world-wide-web at this URL:
   * http://opensource.org/licenses/osl-3.0.php
   * If you did not receive a copy of the license and are unable to
   * obtain it through the world-wide-web, please send an email
   * to license@magentocommerce.com so we can send you a copy immediately.
   *
   * @category    EngageCommerce
   * @package     EngageCommerce_Pinterest
   * @copyright   Copyright (c) 2016 Engage Commerce (http://engagecommerce.io)
   * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
   */
  $pixelHelper = Mage::helper("engagecommerce_pinterest");
  $pixelId = $pixelHelper->getPixelId();
  $pixelArr = array_filter(array_map('trim', explode(',', $pixelId)), 'strlen');
?>

<!-- Engage Commerce: Pinterest Tag Code -->
<?php foreach($pixelArr as $id): ?>
  <img height="1" width="1" alt="" src="//ct.pinterest.com/?tid=<?php echo $id ?>"/>
<?php endforeach; ?>
